import type { Language, LocalizationDictionary } from "./types";

export const localizationConfig: Record<Language, LocalizationDictionary> = {
  ru: {
    "common.free": "FREE",
    "settings.title": "Настройки",
    "settings.continue": "Продолжить",
    "settings.restart": "Начать заново",
    "settings.volume": "Звук: {value}%",
    "settings.language": "Язык: RU",
    "death.title": "Ты проиграл",
    "death.subtitle": "Попробуй еще раз",
    "death.restart": "Начать заново",
    "death.continue": "Продолжить",
    "death.continueForEmerald": "Продолжить за {amount}",
    "lootCase.continue": "Получить",
    "lootCase.extra": "Получить еще",
    "loot.potionTitle": "{size} {name}",
    "loot.potionSize.common": "Малое",
    "loot.potionSize.rare": "Среднее",
    "loot.potionSize.epic": "Большое",
    "levelReward.title": "Выбери награду",
    "shop.title": "Магазин перчаток",
    "shop.find": "НАЙДИ",
    "shop.reachBoss": "ДОЙДИ ДО БОССА",
    "shop.equipped": "НАДЕТО",
    "shop.equip": "НАДЕТЬ",
    "shop.noMoney": "НЕТ",
    "shop.openInInfiniteTower": "В Бесконечной Башне",
    "toast.weaponUnlocked": "Новое оружие",
    "notification.weaponUnlocked": "Новое оружие",
    "notification.newReward": "Новая награда",
    "training.button": "Тренировки",
    "training.loading": "Загрузка...",
    "training.title": "Зал тренировок",
    "training.close": "Закрыть",
    "training.buy": "Купить",
    "training.max": "Макс.",
    "training.level": "Ур. {level}/{max}",
    "training.punchPower.title": "Сила кулака",
    "training.punchPower.description": "+{value} к урону",
    "training.strongJaw.title": "Крепкая челюсть",
    "training.strongJaw.description": "+{value} к здоровью",
    "training.endurance.title": "Дыхалка",
    "training.endurance.description": "+{value} к стамине",
    "training.lightGloves.title": "Легкие перчатки",
    "training.lightGloves.description": "-{value} к затратам",
    "training.fastHands.title": "Быстрые руки",
    "training.fastHands.description": "+{value}% к скорости",
    "infinite.button": "Башня",
    "infinite.lockedTitle": "Бесконечная башня",
    "infinite.lockedDescription": "Пройди игру, чтобы открыть бесконечную башню.",
    "infinite.lockedRewards": "В будущем здесь будут награды за этажи, рекорды и редкие ресурсы.",
    "infinite.unlockedTitle": "Бесконечная башня",
    "infinite.unlockedDescription": "Поднимайся выше и забирай награды за новые этажи.",
    "infinite.subtitle": "Башня не имеет конца. Проверь свои силы",
    "infinite.start": "Старт",
    "infinite.fight": "В бой",
    "infinite.close": "Закрыть",
    "infinite.rewardLocked": "Заблокировано",
    "infinite.rewardClaim": "Забрать",
    "infinite.rewardClaimed": "Получено",
    "infinite.startRewardTitle": "Стартовая награда",
    "infinite.startRewardItem": "Золотые перчатки 67",
    "infinite.diamondGlovesRewardItem": "Алмазные перчатки 67",
    "infinite.sealedTitle": "Башня запечатана",
    "infinite.sealedDescription": "Чтобы открыть Бесконечную башню, одолей Вардена.",
    "infinite.sealedHint": "Победи хранителя и сними печать с башни.",
    "victory.close": "Закрыть",
    "victory.campaign.message": "Поздравляю, ты прошел сюжет, теперь для тебя открыт \"Край\". Также для тебя открыты новые уровни улучшения. Проходи \"Край\", зарабатывай рекорды и получай награды.",
    "buff.rarity.wooden": "Дерево",
    "buff.rarity.golden": "Золото",
    "buff.rarity.emerald": "Изумруд",
    "buff.rarity.diamond": "Алмаз",
    "buff.damage.title": "Сильный удар",
    "buff.damage.description": "+{value} к урону",
    "buff.stamina.title": "Запас сил",
    "buff.stamina.description": "+{value} к выносливости",
    "buff.health.title": "Крепкий корпус",
    "buff.health.description": "+{value} к здоровью",
    "buff.attackSpeed.title": "Быстрые руки",
    "buff.attackSpeed.description": "+{value}% к скорости",
    "buff.staminaCost.title": "Легкий удар",
    "buff.staminaCost.description": "-{value} к затратам",
    "loot.healthPotion.name": "Зелье здоровья",
    "loot.healthPotion.description": "Восстановить {value}% здоровья",
    "loot.staminaPotion.name": "Зелье стамины",
    "loot.staminaPotion.description": "Восстановить {value}% стамины",
    "loot.attackSpeedPotion.name": "Зелье скорости атаки",
    "loot.attackSpeedPotion.description": "+{value}% к скорости атаки",
    "loot.attackPowerPotion.name": "Зелье силы атаки",
    "loot.attackPowerPotion.description": "+{value} к силе атаки",
    "loot.emerald.name": "Изумруды",
    "loot.emerald.name.common": "Изумруды",
    "loot.emerald.name.rare": "Гора изумрудов",
    "loot.emerald.name.epic": "Куча изумрудов",
    "loot.emerald.description": "+{value} изумрудов",
  },
  en: {
    "common.free": "FREE",
    "settings.title": "Settings",
    "settings.continue": "Continue",
    "settings.restart": "Restart",
    "settings.volume": "Sound: {value}%",
    "settings.language": "Language: EN",
    "death.title": "You lost",
    "death.subtitle": "Try again",
    "death.restart": "Restart",
    "death.continue": "Continue",
    "death.continueForEmerald": "Continue for {amount}",
    "lootCase.continue": "Claim",
    "lootCase.extra": "Claim more",
    "loot.potionTitle": "{size} {name}",
    "loot.potionSize.common": "Small",
    "loot.potionSize.rare": "Medium",
    "loot.potionSize.epic": "Large",
    "levelReward.title": "Choose reward",
    "shop.title": "Glove Shop",
    "shop.find": "FIND",
    "shop.reachBoss": "REACH THE BOSS",
    "shop.equipped": "EQUIPPED",
    "shop.equip": "EQUIP",
    "shop.noMoney": "NO",
    "shop.openInInfiniteTower": "In the Endless Tower",
    "toast.weaponUnlocked": "New weapon",
    "notification.weaponUnlocked": "New weapon",
    "notification.newReward": "New reward",
    "training.button": "Training",
    "training.loading": "Loading...",
    "training.title": "Training Hall",
    "training.close": "Close",
    "training.buy": "Buy",
    "training.max": "Max",
    "training.level": "Lv. {level}/{max}",
    "training.punchPower.title": "Punch Power",
    "training.punchPower.description": "+{value} damage",
    "training.strongJaw.title": "Strong Jaw",
    "training.strongJaw.description": "+{value} health",
    "training.endurance.title": "Endurance",
    "training.endurance.description": "+{value} stamina",
    "training.lightGloves.title": "Light Gloves",
    "training.lightGloves.description": "-{value} cost",
    "training.fastHands.title": "Fast Hands",
    "training.fastHands.description": "+{value}% speed",
    "infinite.button": "Tower",
    "infinite.lockedTitle": "Endless Tower",
    "infinite.lockedDescription": "Complete the game to unlock the endless tower.",
    "infinite.lockedRewards": "Future rewards will live here: floors, records, and rare resources.",
    "infinite.unlockedTitle": "Endless Tower",
    "infinite.unlockedDescription": "Climb higher and collect rewards for new floors.",
    "infinite.subtitle": "The tower has no end. Test your strength",
    "infinite.start": "Start",
    "infinite.fight": "Fight",
    "infinite.close": "Close",
    "infinite.rewardLocked": "Locked",
    "infinite.rewardClaim": "Claim",
    "infinite.rewardClaimed": "Claimed",
    "infinite.startRewardTitle": "Starting Reward",
    "infinite.startRewardItem": "Golden Gloves 67",
    "infinite.diamondGlovesRewardItem": "Diamond Gloves 67",
    "infinite.sealedTitle": "Tower Sealed",
    "infinite.sealedDescription": "To unlock the Endless Tower, defeat the Warden.",
    "infinite.sealedHint": "Beat the guardian and break the tower seal.",
    "victory.close": "Close",
    "victory.campaign.message": "Congratulations, you completed the story. The End is now open for you. New upgrade levels are also unlocked. Clear The End, set records, and earn rewards.",
    "buff.rarity.wooden": "Wooden",
    "buff.rarity.golden": "Golden",
    "buff.rarity.emerald": "Emerald",
    "buff.rarity.diamond": "Diamond",
    "buff.damage.title": "Heavy Hit",
    "buff.damage.description": "+{value} damage",
    "buff.stamina.title": "Stamina Reserve",
    "buff.stamina.description": "+{value} stamina",
    "buff.health.title": "Tough Body",
    "buff.health.description": "+{value} health",
    "buff.attackSpeed.title": "Fast Hands",
    "buff.attackSpeed.description": "+{value}% speed",
    "buff.staminaCost.title": "Light Hit",
    "buff.staminaCost.description": "-{value} cost",
    "loot.healthPotion.name": "Health Potion",
    "loot.healthPotion.description": "Restore {value}% health",
    "loot.staminaPotion.name": "Stamina Potion",
    "loot.staminaPotion.description": "Restore {value}% stamina",
    "loot.attackSpeedPotion.name": "Attack Speed Potion",
    "loot.attackSpeedPotion.description": "+{value}% attack speed",
    "loot.attackPowerPotion.name": "Attack Power Potion",
    "loot.attackPowerPotion.description": "+{value} attack power",
    "loot.emerald.name": "Emerald",
    "loot.emerald.name.common": "Emeralds",
    "loot.emerald.name.rare": "Emerald Mountain",
    "loot.emerald.name.epic": "Emerald Pile",
    "loot.emerald.description": "+{value} emeralds",
  },
};
