import type { Language, LocalizationDictionary } from "./types";

export const localizationConfig: Record<Language, LocalizationDictionary> = {
  ru: {
    "common.free": "FREE",
    "loading.generatingLocation": "Генерируем локацию...",
    "onboarding.welcome":
      "О нет, кажется, я попал в мир Майна! Нужно выбираться отсюда, но сначала потренируюсь. Нужно побить грушу!",
    "heroMessage.enemySpawn.1":
      "Ну здравствуй, кубический уродец. Сейчас я из тебя пиксели вытрясу.",
    "heroMessage.enemySpawn.2":
      "Опа! А ты, кажется, думал, что страшный? Миленько.",
    "heroMessage.enemySpawn.3":
      "Вот это я понимаю — мясо само пришло на тренировку.",
    "heroMessage.enemySpawn.4":
      "О нет, враг! Как неожиданно. Ладно, бей первым… ой, уже поздно.",
    "heroMessage.enemySpawn.5":
      "Ну давай, подходи. Я как раз разминался на твоих друзьях.",
    "heroMessage.enemySpawn.6":
      "Если это была засада, то у вас тут хреновый отдел планирования.",
    "heroMessage.enemySpawn.7":
      "Так, кто там ещё шуршит? У меня кулаки скучают.",
    "heroMessage.enemySpawn.8":
      "Ну что, кто следующий хочет стать красивой кучкой ресурсов?",
    "heroMessage.enemySpawn.9":
      "Смотри-ка, ещё один герой нарисовался.",
    "heroMessage.enemySpawn.10":
      "Отлично. А я как раз искал, на ком проверить новый удар.",
    "heroMessage.enemySpawn.11": "О, мясо пришло само.",
    "heroMessage.enemySpawn.12": "Ну здравствуй, уродец.",
    "heroMessage.enemySpawn.13": "А вот и проблема на ножках.",
    "heroMessage.enemySpawn.14":
      "Ты заблудился или умереть пришёл?",
    "heroMessage.enemySpawn.15": "Смотри-ка, ещё один герой.",
    "heroMessage.enemySpawn.16": "Ну давай, удиви меня.",
    "heroMessage.enemySpawn.17": "Опа, свежий мешок лута.",
    "heroMessage.enemySpawn.18": "Кто тебя сюда пустил?",
    "heroMessage.enemySpawn.19": "Отлично, кулаки заскучали.",
    "heroMessage.enemySpawn.20": "Так, это ещё что за чудо?",
    "heroMessage.enemyDeath.1":
      "Лежи спокойно, дружок. Твои блоки теперь мои.",
    "heroMessage.enemyDeath.2":
      "Ха! Минус один идиот в этом квадратном дурдоме.",
    "heroMessage.enemyDeath.3":
      "Да ты посмотри, он ещё и лут уронил. Обожаю воспитанных мерзавцев.",
    "heroMessage.enemyDeath.4":
      "Это было так приятно, что я почти почувствовал себя героем.",
    "heroMessage.enemyDeath.5":
      "Вот так-то, мелкий гад. Не стоило моргать своими пиксельными глазами.",
    "heroMessage.enemyDeath.6":
      "Я пришёл, увидел и врезал. Классика.",
    "heroMessage.enemyDeath.7":
      "Ой, извини, я случайно… А нет, специально.",
    "heroMessage.enemyDeath.8":
      "Ха-ха! Вот это удар! Даже груша бы зауважала.",
    "heroMessage.enemyDeath.9":
      "Ты хотел меня остановить? Милый, ты даже паузу не нажал.",
    "heroMessage.enemyDeath.10":
      "Мир из кубов, враги из картона, а удовольствие настоящее.",
    "heroMessage.enemyDeath.11": "Минус один.",
    "heroMessage.enemyDeath.12": "Лежи красиво.",
    "heroMessage.enemyDeath.13": "Вот и весь твой план.",
    "heroMessage.enemyDeath.14": "Упал, как мешок блоков.",
    "heroMessage.enemyDeath.15": "Следующий!",
    "heroMessage.enemyDeath.16": "Красиво разлетелся.",
    "heroMessage.enemyDeath.17": "Спасибо за лут.",
    "heroMessage.enemyDeath.18": "Даже не вспотел.",
    "heroMessage.enemyDeath.19": "Пиксели к пикселям.",
    "heroMessage.bossSpawn.1":
      "О, здоровяк вышел. Наконец-то кто-то, кого не стыдно ударить два раза.",
    "heroMessage.bossSpawn.2":
      "Ты тут главный? Отлично. Я как раз люблю начинать уборку с самой большой грязи.",
    "heroMessage.bossSpawn.3":
      "Смотри-ка, босс с полоской здоровья. Как мило — даже смерть с интерфейсом.",
    "heroMessage.bossSpawn.4":
      "Ну давай, покажи свой страшный приём. Я потом покажу свой: кулак в лицо.",
    "heroMessage.bossSpawn.5":
      "Вот это размер! Жаль, мозгов тебе всё равно не докинули.",
    "ads.countdown": "До рекламы {seconds}",
    "settings.title": "Настройки",
    "settings.continue": "Продолжить",
    "settings.restart": "Начать заново",
    "settings.volume": "Звук: {value}%",
    "settings.language": "Язык: RU",
    "death.title": "Ты проиграл",
    "death.subtitle": "Попробуй еще раз",
    "death.restart": "Начать заново",
    "death.continue": "Продолжить",
    "death.continueForEmerald": "Продолжить за {amount}",
    "death.continueForRewive": "Продолжить за",
    "death.continueForAd": "Продолжить за",
    "death.rewiveRemaining": "Осталось x{amount}",
    "lootCase.continue": "Получить",
    "lootCase.extra": "Получить еще",
    "loot.potionTitle": "{size} {name}",
    "loot.potionSize.common": "Малое",
    "loot.potionSize.rare": "Среднее",
    "loot.potionSize.epic": "Большое",
    "levelReward.title": "Выбери награду",
    "shop.title": "Магазин перчаток",
    "shop.find": "НАЙДИ",
    "shop.reachBoss": "ДОЙДИ ДО БОССА",
    "shop.equipped": "НАДЕТО",
    "shop.equip": "НАДЕТЬ",
    "shop.noMoney": "НЕТ",
    "shop.openInInfiniteTower": "В Бесконечной Башне",
    "shop.openInDailyReward": "В недельной награде",
    "toast.weaponUnlocked": "Новое оружие",
    "notification.weaponUnlocked": "Новое оружие",
    "notification.newReward": "Новая награда",
    "daily.title": "Ежедневная награда",
    "daily.available": "Забери награду за сегодняшний вход",
    "daily.todayClaimed": "Сегодняшняя награда уже получена",
    "daily.done": "Все награды получены",
    "daily.day": "День {day}",
    "daily.ready": "Готово",
    "daily.claimed": "Забрано",
    "daily.locked": "Дальше",
    "daily.tomorrow": "Завтра",
    "daily.afterDays": "{days} дней",
    "daily.claim": "Забрать",
    "daily.close": "Закрыть",
    "training.button": "Тренировки",
    "training.loading": "Загрузка...",
    "training.title": "Зал тренировок",
    "training.close": "Закрыть",
    "training.buy": "Купить",
    "training.max": "Макс.",
    "training.maximum": "Максимум",
    "training.locked.infinityTower": "Откроется в режиме бесконечной башни",
    "training.infinityUnlocked.message": "Круто ты стал сильнее.\nТеперь тебе доступны самые мощные тренировки",
    "training.level": "Ур. {level}/{max}",
    "training.punchPower.title": "Сила кулака",
    "training.punchPower.description": "+{value} к урону",
    "training.heroPower.title": "Геройская сила",
    "training.heroPower.description": "+{value} к урону",
    "training.strongJaw.title": "Крепкая челюсть",
    "training.strongJaw.description": "+{value} к здоровью",
    "training.heroHealth.title": "Здоровье героя",
    "training.heroHealth.description": "+{value} к здоровью",
    "training.endurance.title": "Дыхалка",
    "training.endurance.description": "+{value} к выносливости",
    "training.heroBreath.title": "Дыхалка героя",
    "training.heroBreath.description": "+{value} к выносливости",
    "training.lightGloves.title": "Легкие перчатки",
    "training.lightGloves.description": "-{value} к затратам",
    "training.fastHands.title": "Быстрые руки",
    "training.fastHands.description": "+{value}% к скорости",
    "training.criticalHit.title": "Орлиный глаз",
    "training.criticalHit.description": "+{value}% к шансу крита",
    "infinite.button": "Башня",
    "infinite.lockedTitle": "Бесконечная башня",
    "infinite.lockedDescription": "Пройди игру, чтобы открыть бесконечную башню.",
    "infinite.lockedRewards": "В будущем здесь будут награды за этажи, рекорды и редкие ресурсы.",
    "infinite.unlockedTitle": "Бесконечная башня",
    "infinite.unlockedDescription": "Поднимайся выше и забирай награды за новые этажи.",
    "infinite.subtitle": "Башня не имеет конца. Проверь свои силы",
    "infinite.start": "Старт",
    "infinite.fight": "В бой",
    "infinite.close": "Закрыть",
    "infinite.rewardLocked": "Заблокировано",
    "infinite.rewardClaim": "Забрать",
    "infinite.rewardClaimed": "Получено",
    "infinite.rewardDetails.title": "Новый предмет",
    "infinite.rewardDetails.rewive": "Воскрешает бесплатно после поражения",
    "infinite.rewardDetails.attackSpeedPotion": "Увеличивает скорость атаки в забеге",
    "infinite.rewardDetails.attackPowerPotion": "Увеличивает силу атаки в забеге",
    "infinite.rewardDetails.gloves": "Новые перчатки, еще больше силы! Посмотри в магазине",
    "infinite.rewardDetails.emerald": "Ого, нужно скорее прокачаться",
    "infinite.consumable.question": "Выпить зелье?",
    "infinite.consumable.no": "Нет",
    "infinite.consumable.attackSpeed": "Зелье скорости атаки",
    "infinite.consumable.attackPower": "Зелье силы атаки",
    "infinite.startRewardTitle": "Стартовая награда",
    "infinite.startRewardItem": "Золотые перчатки 67",
    "infinite.diamondGlovesRewardItem": "Алмазные перчатки 67",
    "infinite.sealedTitle": "Башня запечатана",
    "infinite.sealedDescription": "Чтобы открыть Бесконечную башню, одолей Вардена.",
    "infinite.sealedHint": "Победи хранителя и сними печать с башни.",
    "victory.close": "Закрыть",
    "victory.campaign.title": "Победа!",
    "victory.campaign.message": "Открыт новый режим - Башня бесконечности\nТеперь тебе доступны новые награды, усиления, перчатки и многое другое\nПоднимайся все выше, становись сильнее и побеждай других в рейтинге!",
    "buff.rarity.wooden": "Дерево",
    "buff.rarity.golden": "Золото",
    "buff.rarity.emerald": "Изумруд",
    "buff.rarity.diamond": "Алмаз",
    "buff.damage.title": "Сильный удар",
    "buff.damage.description": "+{value} к урону",
    "buff.stamina.title": "Запас сил",
    "buff.stamina.description": "+{value} к выносливости",
    "buff.health.title": "Крепкий корпус",
    "buff.health.description": "+{value} к здоровью",
    "buff.attackSpeed.title": "Быстрые руки",
    "buff.attackSpeed.description": "+{value}% к скорости",
    "buff.staminaCost.title": "Легкий удар",
    "buff.staminaCost.description": "-{value} к затратам",
    "loot.healthPotion.name": "Зелье здоровья",
    "loot.healthPotion.description": "Восстановить {value}% здоровья",
    "loot.staminaPotion.name": "Зелье выносливости",
    "loot.staminaPotion.description": "Восстановить {value}% выносливости",
    "loot.attackSpeedPotion.name": "Зелье скорости атаки",
    "loot.attackSpeedPotion.description": "+{value}% к скорости атаки",
    "loot.attackPowerPotion.name": "Зелье силы атаки",
    "loot.attackPowerPotion.description": "+{value} к силе атаки",
    "loot.emerald.name": "Изумруды",
    "loot.emerald.name.common": "Изумруды",
    "loot.emerald.name.rare": "Гора изумрудов",
    "loot.emerald.name.epic": "Куча изумрудов",
    "loot.emerald.description": "+{value} изумрудов",
  },
  en: {
    "common.free": "FREE",
    "loading.generatingLocation": "Generating location...",
    "onboarding.welcome":
      "Oh no, it looks like I ended up in the world of Mine! I need to get out, but first I should train. Time to hit the punching bag!",
    "heroMessage.enemySpawn.1":
      "Well hello, you blocky freak. Time to shake the pixels out of you.",
    "heroMessage.enemySpawn.2":
      "Oh! You actually thought you looked scary? That's adorable.",
    "heroMessage.enemySpawn.3":
      "Now that's service — the punching meat came to training by itself.",
    "heroMessage.enemySpawn.4":
      "Oh no, an enemy! What a surprise. Fine, hit first... oops, too late.",
    "heroMessage.enemySpawn.5":
      "Come on, step closer. I was just warming up on your friends.",
    "heroMessage.enemySpawn.6":
      "If this was an ambush, your planning department really sucks.",
    "heroMessage.enemySpawn.7":
      "Who's making noise over there? My fists are getting bored.",
    "heroMessage.enemySpawn.8":
      "All right, who wants to become a nice little pile of resources next?",
    "heroMessage.enemySpawn.9":
      "Look at that, another hero just showed up.",
    "heroMessage.enemySpawn.10":
      "Perfect. I was looking for someone to test my new punch on.",
    "heroMessage.enemySpawn.11": "Oh, the punching meat came by itself.",
    "heroMessage.enemySpawn.12": "Well hello, ugly.",
    "heroMessage.enemySpawn.13": "And here's trouble on two legs.",
    "heroMessage.enemySpawn.14": "Are you lost, or did you come here to die?",
    "heroMessage.enemySpawn.15": "Look at that, another hero.",
    "heroMessage.enemySpawn.16": "Come on, surprise me.",
    "heroMessage.enemySpawn.17": "Oh, a fresh bag of loot.",
    "heroMessage.enemySpawn.18": "Who let you in here?",
    "heroMessage.enemySpawn.19": "Perfect, my fists were getting bored.",
    "heroMessage.enemySpawn.20": "All right, what kind of freak is this?",
    "heroMessage.enemyDeath.1":
      "Lie still, buddy. Your blocks belong to me now.",
    "heroMessage.enemyDeath.2":
      "Ha! One less idiot in this square madhouse.",
    "heroMessage.enemyDeath.3":
      "Look at that, it even dropped loot. I love well-mannered scumbags.",
    "heroMessage.enemyDeath.4":
      "That felt so good I almost felt like a hero.",
    "heroMessage.enemyDeath.5":
      "That's what you get, little creep. Shouldn't have blinked those pixel eyes.",
    "heroMessage.enemyDeath.6":
      "I came, I saw, I punched. Classic.",
    "heroMessage.enemyDeath.7":
      "Oops, sorry, that was an accident... Nope, totally on purpose.",
    "heroMessage.enemyDeath.8":
      "Ha-ha! What a punch! Even the training bag would respect that.",
    "heroMessage.enemyDeath.9":
      "You wanted to stop me? Sweetie, you couldn't even hit pause.",
    "heroMessage.enemyDeath.10":
      "A world of blocks, enemies made of cardboard, and the fun is real.",
    "heroMessage.enemyDeath.11": "That's one less.",
    "heroMessage.enemyDeath.12": "Try to look pretty lying there.",
    "heroMessage.enemyDeath.13": "So that was your whole plan.",
    "heroMessage.enemyDeath.14": "Dropped like a sack of blocks.",
    "heroMessage.enemyDeath.15": "Next!",
    "heroMessage.enemyDeath.16": "That was a beautiful explosion.",
    "heroMessage.enemyDeath.17": "Thanks for the loot.",
    "heroMessage.enemyDeath.18": "Didn't even break a sweat.",
    "heroMessage.enemyDeath.19": "Pixel by pixel.",
    "heroMessage.bossSpawn.1":
      "Oh, the big guy is here. Finally, someone worth punching twice.",
    "heroMessage.bossSpawn.2":
      "You're the boss here? Great. I like to start cleaning with the biggest mess.",
    "heroMessage.bossSpawn.3":
      "Look at that, a boss with a health bar. Cute — even death has an interface.",
    "heroMessage.bossSpawn.4":
      "Come on, show me your scary move. Then I'll show you mine: fist to the face.",
    "heroMessage.bossSpawn.5":
      "Look at that size! Too bad they still forgot to give you brains.",
    "ads.countdown": "Ad in {seconds}",
    "settings.title": "Settings",
    "settings.continue": "Continue",
    "settings.restart": "Restart",
    "settings.volume": "Sound: {value}%",
    "settings.language": "Language: EN",
    "death.title": "You lost",
    "death.subtitle": "Try again",
    "death.restart": "Restart",
    "death.continue": "Continue",
    "death.continueForEmerald": "Continue for {amount}",
    "death.continueForRewive": "Continue for",
    "death.continueForAd": "Continue for",
    "death.rewiveRemaining": "Left x{amount}",
    "lootCase.continue": "Claim",
    "lootCase.extra": "Claim more",
    "loot.potionTitle": "{size} {name}",
    "loot.potionSize.common": "Small",
    "loot.potionSize.rare": "Medium",
    "loot.potionSize.epic": "Large",
    "levelReward.title": "Choose reward",
    "shop.title": "Glove Shop",
    "shop.find": "FIND",
    "shop.reachBoss": "REACH THE BOSS",
    "shop.equipped": "EQUIPPED",
    "shop.equip": "EQUIP",
    "shop.noMoney": "NO",
    "shop.openInInfiniteTower": "In the Endless Tower",
    "shop.openInDailyReward": "In weekly reward",
    "toast.weaponUnlocked": "New weapon",
    "notification.weaponUnlocked": "New weapon",
    "notification.newReward": "New reward",
    "daily.title": "Daily Reward",
    "daily.available": "Claim today's login reward",
    "daily.todayClaimed": "Today's reward is already claimed",
    "daily.done": "All rewards claimed",
    "daily.day": "Day {day}",
    "daily.ready": "Ready",
    "daily.claimed": "Claimed",
    "daily.locked": "Next",
    "daily.tomorrow": "Tomorrow",
    "daily.afterDays": "{days} days",
    "daily.claim": "Claim",
    "daily.close": "Close",
    "training.button": "Training",
    "training.loading": "Loading...",
    "training.title": "Training Hall",
    "training.close": "Close",
    "training.buy": "Buy",
    "training.max": "Max",
    "training.maximum": "Maximum",
    "training.locked.infinityTower": "Unlocks in Infinite Tower mode",
    "training.infinityUnlocked.message": "Nice, you got stronger.\nThe most powerful training is now available",
    "training.level": "Lv. {level}/{max}",
    "training.punchPower.title": "Punch Power",
    "training.punchPower.description": "+{value} damage",
    "training.heroPower.title": "Heroic Power",
    "training.heroPower.description": "+{value} damage",
    "training.strongJaw.title": "Strong Jaw",
    "training.strongJaw.description": "+{value} health",
    "training.heroHealth.title": "Hero Health",
    "training.heroHealth.description": "+{value} health",
    "training.endurance.title": "Endurance",
    "training.endurance.description": "+{value} stamina",
    "training.heroBreath.title": "Hero Breath",
    "training.heroBreath.description": "+{value} stamina",
    "training.lightGloves.title": "Light Gloves",
    "training.lightGloves.description": "-{value} cost",
    "training.fastHands.title": "Fast Hands",
    "training.fastHands.description": "+{value}% speed",
    "training.criticalHit.title": "Eagle Eye",
    "training.criticalHit.description": "+{value}% critical chance",
    "infinite.button": "Tower",
    "infinite.lockedTitle": "Endless Tower",
    "infinite.lockedDescription": "Complete the game to unlock the endless tower.",
    "infinite.lockedRewards": "Future rewards will live here: floors, records, and rare resources.",
    "infinite.unlockedTitle": "Endless Tower",
    "infinite.unlockedDescription": "Climb higher and collect rewards for new floors.",
    "infinite.subtitle": "The tower has no end. Test your strength",
    "infinite.start": "Start",
    "infinite.fight": "Fight",
    "infinite.close": "Close",
    "infinite.rewardLocked": "Locked",
    "infinite.rewardClaim": "Claim",
    "infinite.rewardClaimed": "Claimed",
    "infinite.rewardDetails.title": "New item",
    "infinite.rewardDetails.rewive": "Revives you for free after defeat",
    "infinite.rewardDetails.attackSpeedPotion": "Increases attack speed for the run",
    "infinite.rewardDetails.attackPowerPotion": "Increases attack power for the run",
    "infinite.rewardDetails.gloves": "New gloves, even more power! Check the shop",
    "infinite.rewardDetails.emerald": "Whoa, time to upgrade fast",
    "infinite.consumable.question": "Drink a potion?",
    "infinite.consumable.no": "No",
    "infinite.consumable.attackSpeed": "Attack Speed Potion",
    "infinite.consumable.attackPower": "Attack Power Potion",
    "infinite.startRewardTitle": "Starting Reward",
    "infinite.startRewardItem": "Golden Gloves 67",
    "infinite.diamondGlovesRewardItem": "Diamond Gloves 67",
    "infinite.sealedTitle": "Tower Sealed",
    "infinite.sealedDescription": "To unlock the Endless Tower, defeat the Warden.",
    "infinite.sealedHint": "Beat the guardian and break the tower seal.",
    "victory.close": "Close",
    "victory.campaign.title": "Victory!",
    "victory.campaign.message": "A new mode is open - Infinity Tower\n\nNew rewards, boosts, gloves, and much more are now available\n\nClimb higher, grow stronger, and beat others on the leaderboard!",
    "buff.rarity.wooden": "Wooden",
    "buff.rarity.golden": "Golden",
    "buff.rarity.emerald": "Emerald",
    "buff.rarity.diamond": "Diamond",
    "buff.damage.title": "Heavy Hit",
    "buff.damage.description": "+{value} damage",
    "buff.stamina.title": "Stamina Reserve",
    "buff.stamina.description": "+{value} stamina",
    "buff.health.title": "Tough Body",
    "buff.health.description": "+{value} health",
    "buff.attackSpeed.title": "Fast Hands",
    "buff.attackSpeed.description": "+{value}% speed",
    "buff.staminaCost.title": "Light Hit",
    "buff.staminaCost.description": "-{value} cost",
    "loot.healthPotion.name": "Health Potion",
    "loot.healthPotion.description": "Restore {value}% health",
    "loot.staminaPotion.name": "Stamina Potion",
    "loot.staminaPotion.description": "Restore {value}% stamina",
    "loot.attackSpeedPotion.name": "Attack Speed Potion",
    "loot.attackSpeedPotion.description": "+{value}% attack speed",
    "loot.attackPowerPotion.name": "Attack Power Potion",
    "loot.attackPowerPotion.description": "+{value} attack power",
    "loot.emerald.name": "Emerald",
    "loot.emerald.name.common": "Emeralds",
    "loot.emerald.name.rare": "Emerald Mountain",
    "loot.emerald.name.epic": "Emerald Pile",
    "loot.emerald.description": "+{value} emeralds",
  },
};
