import type { Language, LocalizationDictionary } from "./types";

export const localizationConfig: Record<Language, LocalizationDictionary> = {
  ru: {
    "common.free": "FREE",
    "settings.title": "Настройки",
    "settings.continue": "Продолжить",
    "settings.restart": "Начать заново",
    "settings.volume": "Звук: {value}%",
    "settings.language": "Язык: RU",
    "death.title": "Ты проиграл",
    "death.subtitle": "Попробуй еще раз",
    "death.restart": "Начать заново",
    "death.continue": "Продолжить",
    "death.continueForEmerald": "Продолжить за {amount}",
    "lootCase.continue": "Получить",
    "lootCase.extra": "Получить еще",
    "loot.potionTitle": "{size} {name}",
    "loot.potionSize.common": "Малое",
    "loot.potionSize.rare": "Среднее",
    "loot.potionSize.epic": "Большое",
    "levelReward.title": "Выбери награду",
    "shop.find": "НАЙДИ",
    "shop.equipped": "НАДЕТО",
    "shop.equip": "НАДЕТЬ",
    "shop.noMoney": "НЕТ",
    "toast.weaponUnlocked": "Открыто новое оружие",
    "training.button": "Тренировки",
    "training.loading": "Загрузка...",
    "training.title": "Зал тренировок",
    "training.close": "Закрыть",
    "training.buy": "Купить",
    "training.max": "Макс.",
    "training.level": "Ур. {level}/{max}",
    "training.punchPower.title": "Сила кулака",
    "training.punchPower.description": "+{value} к урону",
    "training.strongJaw.title": "Крепкая челюсть",
    "training.strongJaw.description": "+{value} к здоровью",
    "training.endurance.title": "Дыхалка",
    "training.endurance.description": "+{value} к стамине",
    "training.lightGloves.title": "Легкие перчатки",
    "training.lightGloves.description": "-{value} к затратам",
    "training.fastHands.title": "Быстрые руки",
    "training.fastHands.description": "+{value}% к скорости",
    "buff.rarity.wooden": "Дерево",
    "buff.rarity.golden": "Золото",
    "buff.rarity.emerald": "Изумруд",
    "buff.rarity.diamond": "Алмаз",
    "buff.damage.title": "Сильный удар",
    "buff.damage.description": "+{value} к урону",
    "buff.stamina.title": "Запас сил",
    "buff.stamina.description": "+{value} к выносливости",
    "buff.health.title": "Крепкий корпус",
    "buff.health.description": "+{value} к здоровью",
    "buff.attackSpeed.title": "Быстрые руки",
    "buff.attackSpeed.description": "+{value}% к скорости",
    "buff.staminaCost.title": "Легкий удар",
    "buff.staminaCost.description": "-{value} к затратам",
    "loot.healthPotion.name": "Зелье здоровья",
    "loot.healthPotion.description": "Восстановить {value}% здоровья",
    "loot.staminaPotion.name": "Зелье стамины",
    "loot.staminaPotion.description": "Восстановить {value}% стамины",
    "loot.attackSpeedPotion.name": "Зелье скорости атаки",
    "loot.attackSpeedPotion.description": "+{value}% к скорости атаки",
    "loot.attackPowerPotion.name": "Зелье силы атаки",
    "loot.attackPowerPotion.description": "+{value} к силе атаки",
    "loot.emerald.name": "Изумруды",
    "loot.emerald.name.common": "Изумруды",
    "loot.emerald.name.rare": "Гора изумрудов",
    "loot.emerald.name.epic": "Куча изумрудов",
    "loot.emerald.description": "+{value} emerald",
  },
  en: {
    "common.free": "FREE",
    "settings.title": "Settings",
    "settings.continue": "Continue",
    "settings.restart": "Restart",
    "settings.volume": "Sound: {value}%",
    "settings.language": "Language: EN",
    "death.title": "You lost",
    "death.subtitle": "Try again",
    "death.restart": "Restart",
    "death.continue": "Continue",
    "death.continueForEmerald": "Continue for {amount}",
    "lootCase.continue": "Claim",
    "lootCase.extra": "Claim more",
    "loot.potionTitle": "{size} {name}",
    "loot.potionSize.common": "Small",
    "loot.potionSize.rare": "Medium",
    "loot.potionSize.epic": "Large",
    "levelReward.title": "Choose reward",
    "shop.find": "FIND",
    "shop.equipped": "EQUIPPED",
    "shop.equip": "EQUIP",
    "shop.noMoney": "NO",
    "toast.weaponUnlocked": "New weapon unlocked",
    "training.button": "Training",
    "training.loading": "Loading...",
    "training.title": "Training Hall",
    "training.close": "Close",
    "training.buy": "Buy",
    "training.max": "Max",
    "training.level": "Lv. {level}/{max}",
    "training.punchPower.title": "Punch Power",
    "training.punchPower.description": "+{value} damage",
    "training.strongJaw.title": "Strong Jaw",
    "training.strongJaw.description": "+{value} health",
    "training.endurance.title": "Endurance",
    "training.endurance.description": "+{value} stamina",
    "training.lightGloves.title": "Light Gloves",
    "training.lightGloves.description": "-{value} cost",
    "training.fastHands.title": "Fast Hands",
    "training.fastHands.description": "+{value}% speed",
    "buff.rarity.wooden": "Wooden",
    "buff.rarity.golden": "Golden",
    "buff.rarity.emerald": "Emerald",
    "buff.rarity.diamond": "Diamond",
    "buff.damage.title": "Heavy Hit",
    "buff.damage.description": "+{value} damage",
    "buff.stamina.title": "Stamina Reserve",
    "buff.stamina.description": "+{value} stamina",
    "buff.health.title": "Tough Body",
    "buff.health.description": "+{value} health",
    "buff.attackSpeed.title": "Fast Hands",
    "buff.attackSpeed.description": "+{value}% speed",
    "buff.staminaCost.title": "Light Hit",
    "buff.staminaCost.description": "-{value} cost",
    "loot.healthPotion.name": "Health Potion",
    "loot.healthPotion.description": "Restore {value}% health",
    "loot.staminaPotion.name": "Stamina Potion",
    "loot.staminaPotion.description": "Restore {value}% stamina",
    "loot.attackSpeedPotion.name": "Attack Speed Potion",
    "loot.attackSpeedPotion.description": "+{value}% attack speed",
    "loot.attackPowerPotion.name": "Attack Power Potion",
    "loot.attackPowerPotion.description": "+{value} attack power",
    "loot.emerald.name": "Emerald",
    "loot.emerald.name.common": "Emeralds",
    "loot.emerald.name.rare": "Emerald Mountain",
    "loot.emerald.name.epic": "Emerald Pile",
    "loot.emerald.description": "+{value} emerald",
  },
};
